name = "VRP"
uuid = "f98c3fd8-b608-4bb0-bfe7-f809f9aaad7e"
authors = ["Anmol Pahwa"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
